# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ElectronBuild
on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python dependencies
      working-directory: perico
      run: |
        python -m pip install --upgrade pip
        python install.py
    - name: build python exe
      working-directory: perico
      run: python pack.py

    - name: build electron
      working-directory: ui
      run: |
        npm ci
        npm run buildall

    - name: Upload binaries to release
      if: ${{ github.event_name == 'release'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.YZH_TOKEN }}
        file: ui/build/gta-helper Setup 1.0.0.exe
        asset_name: gta-helper.exe
        tag: ${{ github.ref }}
    